services:
  php-apache:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: "./php-apache/000-default.conf"
        target: "/etc/apache2/sites-enabled/000-default.conf"
      - type: bind
        source: "./php-apache/app"
        target: "/var/www/app"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - type: bind
        source: "./mysql/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker_training
